# Generated by Django 5.1.1 on 2024-10-07 09:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('sol', models.BooleanField(default=True)),
                ('sl_no', models.IntegerField(blank=True, null=True)),
                ('h1', models.CharField(max_length=156)),
                ('slug', models.CharField(blank=True, max_length=1256, null=True)),
                ('page_name', models.CharField(blank=True, max_length=1256, null=True)),
                ('keyword', models.CharField(max_length=156)),
                ('description', models.CharField(blank=True, max_length=900, null=True)),
                ('description1', models.CharField(blank=True, max_length=900, null=True)),
                ('title', models.CharField(max_length=156)),
                ('breadcrumb', models.CharField(max_length=156)),
                ('canonical', models.CharField(default='https://kenshinegroup.com/service/', max_length=900)),
                ('og_type', models.CharField(max_length=156)),
                ('og_card', models.CharField(max_length=156)),
                ('og_site', models.CharField(max_length=156)),
                ('og_title', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=100, null=True)),
                ('og_description', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(upload_to='SEO')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banner')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='SEO')),
                ('updated', models.DateField(auto_now=True)),
                ('blog_banner_lg', models.ImageField(blank=True, null=True, upload_to='data')),
                ('published', models.DateField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('edits', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('schema', models.TextField(blank=True, null=True)),
                ('category', models.ManyToManyField(to='home.category')),
                ('tag', models.ManyToManyField(to='home.tags')),
            ],
        ),
    ]
